-- 5.1 Створити таблицю описів значень атрибутів екземплярів об'єктів.
CREATE TABLE ATTRIBUTES (
	ATTR_ID NUMBER(10),
	OBJECT_ID NUMBER(20),
	VALUE VARCHAR2(4000),
	DATE_VALUE DATE,
	LIST_VALUE_ID NUMBER(10)
);

ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_PK
	PRIMARY KEY (ATTR_ID, OBJECT_ID);
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_LIST_VALUE_ID_FK
	FOREIGN KEY (LIST_VALUE_ID) REFERENCES LISTS (LIST_VALUE_ID);
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_ATTR_ID_FK
	FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID);
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_OBJECT_ID_FK
	FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID);




-- 5.2 На основі вмісту двох рядків двох таблиць, заповнених у лабораторній роботі No3, та опису
-- атрибутів екземплярів об'єктів, заповнити описи значень атрибутів екземплярів об'єктів.
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (1, 1, 'Петро', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (2, 1, 'Петров', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (3, 1, 'Петрович', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (4, 1, NULL, '01/01/2000', NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (5, 1, 'КК112233', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (6, 1, 'вул. Нижня, 50', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (7, 1, '+380123456789', NULL, NULL);

INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (1, 2, 'Іван', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (2, 2, 'Іванов', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (3, 2, NULL, NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (4, 2, NULL, '03/08/1992', NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (5, 2, '001234567', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (6, 2, 'вул. Верхня, 2А', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (7, 2, '+380987654321', NULL, NULL);


INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (8, 3, 'ВН0000АА', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (9, 3, 'ЗАЗ', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (10, 3, 'Чорний', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (11, 3, NULL, '01/01/2005', NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (12, 3, NULL, NULL, 1);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (13, 3, 2, NULL, NULL);

INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (8, 4, 'АА0000АА', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (9, 4, 'ПАЗ', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (10, 4, 'Синій', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (11, 4, NULL, '01/01/1991', NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (12, 4, NULL, NULL, 2);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (13, 4, 5, NULL, NULL);

-- 5.3 Модифікувати рішення завдання 4.3, отримавши колекцію екземплярів об'єктів за заданим
-- значенням одного з атрибутів об'єктів.
SELECT 
    CAR.OBJECT_ID,
    CAR.NAME,
    ATTR.VALUE AS BRAND
FROM OBJECTS CAR, OBJTYPE OT, ATTRIBUTES ATTR
WHERE 	
    OT.CODE = 'Car' 
	AND OT.OBJECT_TYPE_ID = CAR.OBJECT_TYPE_ID
    AND ATTR.VALUE = 'ПАЗ'
    AND ATTR.OBJECT_ID = CAR.OBJECT_ID;

-- OBJECT_ID|NAME        |BRAND|
-- ---------+------------+-----+
--         4|ПАЗ АА0000АА|ПАЗ  |