-- 6.1 Створити таблицю описів зв'язків "іменована асоціація" між екземплярами об'єктів.
CREATE TABLE OBJREFERENCE (
	ATTR_ID   NUMBER(20),
	REFERENCE NUMBER(20),
	OBJECT_ID NUMBER(20)
);

ALTER TABLE OBJREFERENCE ADD CONSTRAINT OBJREFERENCE_PK
	PRIMARY KEY (ATTR_ID,REFERENCE,OBJECT_ID);
ALTER TABLE OBJREFERENCE ADD CONSTRAINT OBJREFERENCE_REFERENCE_FK
	FOREIGN KEY(REFERENCE) REFERENCES OBJECTS(OBJECT_ID);
ALTER TABLE OBJREFERENCE ADD CONSTRAINT OBJREFERENCE_OBJECT_ID_FK
	FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS(OBJECT_ID);
ALTER TABLE OBJREFERENCE ADD CONSTRAINT OBJREFERENCE_ATTR_ID_FK
	FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID);




-- 6.2 Заповнити таблицю зв'язків з урахуванням можливих зв'язків «іменована асоціація» між
-- раніше створеними екземплярами об'єктів класів.

-- Створімо об'єкти паркомісць, з якими можливі іменовані асоціації:
INSERT INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (5, NULL, 3, '001 1 поверх', NULL);
INSERT INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (6, NULL, 3, '002 Надворі', NULL);


INSERT INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) 
VALUES (18, 3, 5);
INSERT INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) 
VALUES (18, 4, 6);