CREATE OR REPLACE VIEW ATTRIBUTE_VIEW
    (OBJ_CODE, ATTR_ID, ATTR_CODE, ATTR_NAME, OBJ_REF)
AS
SELECT O.CODE, A.ATTR_ID, A.CODE, A.NAME, O_REF.CODE O_REF
FROM OBJTYPE O, ATTRTYPE A LEFT JOIN OBJTYPE O_REF ON 
    (A.OBJECT_TYPE_ID_REF = O_REF.OBJECT_TYPE_ID)
WHERE O.OBJECT_TYPE_ID = A.OBJECT_TYPE_ID
ORDER BY A.OBJECT_TYPE_ID, A.ATTR_ID
WITH READ ONLY;

SELECT * FROM ATTRIBUTE_VIEW;